### ISSUE TITLE
Allow default to return Object when no entry is made

### ISSUE THREAD

**Issue by danielpclark** [JEG2/highline#112]
In the example of setting a default `ask("Company? ") { |q| q.default = "none" }` the default string is returned.  When `default = nil` it converts to String without any problems and returns a blank String when no entry is made `""` and not `nil`.  If `false` and most other Objects are used it displays the default `|false|` or equivelant, but then will fail when [enter] is hit with `TypeError: no implicit conversion of false into String`.

I suggest that if the default is set to a non-String Object then it not display the default in the input console (eg: no `|false|`) and return the Object when only [enter] is hit.

```ruby
x = ask("Hit [Enter] to abort or type [y] and [Enter] to proceed:") { |q|
  q.default = false
} and "It is #{!!x} that you entered text.  The text is #{x}."
# => Hit [Enter] to abort or type [y] and [Enter] to proceed: 
```

Which will assign x either `false` or if the instructions are followed it will be `"It is true that you entered text.  The text is y."`

**Comment by abinoam** [comment]
@danielpclark and what about Symbol. Nowadays Symbol and String are used interchangeably.
I think Symbol should appear also, as a "String" object.

I'll take a look on the issue.

**Comment by danielpclark** [comment]
@abinoam  Good catch!  I agree.  Usage of symbol would work great "appearing" as a String.  So it should appear as a String in the display but still return the symbol.

**Comment by abinoam** [comment]
@danielpclark, I've added a failing test at 0264785
I'll try to work on it soon.

**Comment by abinoam** [comment]
I have rebased on master. So commit number has changed to 25a19d2

**Comment by abinoam** [comment]
Hi @danielpclark , I've just added a PR (#121). I think it is what you have suggested. :+1:
