### ISSUE TITLE
question.limit incompatible with question.readline

### ISSUE THREAD

**Issue by brandondrew** [JEG2/highline#113]
If I run this code as it is, the question never appears.  If I remove either the `limit` or the `readline` options, the question appears.
~~~
  ask("Question? ") do |question|
    question.limit                 = 50
    question.readline              = true
  end
~~~

**Comment by abinoam** [comment]
Hi @JEG2,

Is it love what HighLine is in need?

Here is some :heart_eyes::heart::kissing_heart: to it, boxed in a PR (#120). :wink:

**Comment by abinoam** [comment]
@brandondrew, could you check if it works cleanly in your setup?

**Comment by JEG2** [comment]
We'll reopen this if @brandondrew reports trouble with your fix.
