### ISSUE TITLE
:grey is not an alias for :gray

### ISSUE THREAD

**Issue by muflax** [JEG2/highline#114]
I've fallen into this trap at least a dozen times over the last year: "HighLine.color(text, :gr.. was it :gray or :grey?... :grey, I guess... NOPE)". 

Unfortunately I can't file bugs for English itself, so at least :grey should be an alias for :gray everywhere in highline. Would be super-awesome.

Similarly, "bright" vs. "light", though I'm not sure if "bright" is like the official term, and I'm just getting interference from some other terminal app? Still would be nice if I didn't have to remember this arbitrary fact either.

(I've also tripped over "text.redish" as opposed to "text.reddish", but at least that's systematic. Can live with that.)

**Comment by JEG2** [comment]
I never run into this issue for some strange reason…

James Edward **Gray** II

:stuck_out_tongue_winking_eye:

**Comment by JEG2** [comment]
Seriously, I'll merge a patch.  The request seems reasonable to me.

**Comment by muflax** [comment]
Sure, I'll give it a shot.

**Comment by abinoam** [comment]
Hi @muflax ,

GREY is GRAY on https://github.com/abinoam/highline/commit/9db0f38aeb8f45a61853d9f9cedc98f6aae617d9

But that Light and Bright thing, well... I'm not a native english speaker and light blue for me sounds much more like a "not that bright" blue.

Do you natives agree that "light blue" is the same of "bright blue"? If so, I may proceed to implement it.

**Comment by muflax** [comment]
Cool, thanks! 

Yeah, "light blue" and "bright blue" aren't really the same color, but I still find it hard to remember which one the lib used, especially because in many color themes, "bright blue" is just a lighter blue anyway. (And if you google ""light blue" ANSI color", you'll see that a lot of people use the names interchangeably.) 

So I'd still prefer an alias for light/bright, but it's a bit sloppy, yeah.

**Comment by muflax** [comment]
(Also, I noticed that String.redish etc is from awesome_print, so uh, nevermind about that, I'll open an issue there...)

**Comment by abinoam** [comment]
@muflax , I have opened a pull request where grey is gray and also light is bright.
#119
