### ISSUE TITLE
Ask warning "You must enter a valid HighLine::String" for cyrillic strings

### ISSUE THREAD

**Issue by M1chael** [JEG2/highline#115]
If I just typing cyrillic string and press enter, it's all ok. But if I use backspace for delete some part of input and then press enter, HighLine gives me warning "You must enter a valid HighLine::String".

**Comment by JEG2** [comment]
Our support of backspace must not be encoding aware.  We do need to fix that.

**Comment by M1chael** [comment]
Sometimes it crashes with error "invalid byte sequence in UTF-8" after backspacing part of input and submitting string.
