### ISSUE TITLE
Use markdown on Changelog

### ISSUE THREAD

**Issue by abinoam** [JEG2/highline#126]
As used by:
- RSpec https://github.com/rspec/rspec-core/blob/master/Changelog.md
- Rails https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md

It renders pretty nicely on GitHub. At the same time is readable in raw format (https://raw.githubusercontent.com/rspec/rspec-core/master/Changelog.md)

**Comment by JEG2** [comment]
That's fine by me.  Feel free to make the switch.  Just be aware of this:

https://github.com/JEG2/highline/blob/master/Rakefile#L16-L18

**Comment by abinoam** [comment]
Ooops... thanks for pointing it.
Working on this now.
