### ISSUE TITLE
Update Rakefile to remove unused tasks and fix what is possible

### ISSUE THREAD

**Issue by abinoam** [JEG2/highline#127]
Some tasks in Rakefile are there as legacy!
I'll try to refresh Rakefile as we are preparing for release the next version.

**Comment by JEG2** [comment]
Perfect.  Thanks!

**Comment by abinoam** [comment]
Are you still using the "svn" task for anything?

**Comment by JEG2** [comment]
Nope.  It can go.  Thanks.

**Comment by abinoam** [comment]
:+1:
