### ISSUE TITLE
Highline 1.7.0 breaks on Ruby <1.9.3

### ISSUE THREAD

**Issue by elyscape** [JEG2/highline#129]
Commit 3d4ec58 introduced an unconditional require on `io/console`, which was added in Ruby 1.9.3.  Since there is no rescue against `LoadError`, Highline 1.7.0 cannot be used on versions of Ruby prior to 1.9.3.

**Comment by JEG2** [comment]
That's a fair point.  It seems we've lost some older version compatibility.  We should probably investigate this.

**Comment by elyscape** [comment]
This is actually a pretty simple fix.  Basically, move line 9 of 3d4ec58 down to before line 227 and then wrap that segment in a `Rescue LoadError`.  Something like:
```ruby
begin
  require "io/console"
  return winsize if (winsize = IO.console.winsize rescue nil)
rescue LoadError
end
```

**Comment by viyh** [comment]
This is broken on Ruby 2 as well.

ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-linux]

**Comment by JEG2** [comment]
For the same issue?  Ruby 2.0 includes `io/console`.

**Comment by JEG2** [comment]
@abinoam Can you investigate this issue, when you have a chance?

**Comment by markwetter** [comment]
With Ruby 2.0 we had to install io-console to get past this error.

Should io-console be added as a runtime dependency in the gemspec?

**Comment by JEG2** [comment]
`io/console` is a standard library now, but this might be a fix for earlier Rubies.

**Comment by markwetter** [comment]
```ruby
irb(main):001:0> RUBY_VERSION
=> "2.0.0"
irb(main):002:0> require "io/console"
LoadError: cannot load such file -- io/console
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):2
	from /usr/bin/irb:12:in `<main>'
```

**Comment by abinoam** [comment]
Thanks for reporting.
@JEG2, I'll take a look at it.

**Comment by elyscape** [comment]
In the meantime, I have submitted PR #130, which adds support for [Travis CI](https://travis-ci.org/) to the repository.  This should help avoid similar issues in the future.

**Comment by JEG2** [comment]
Sorry @markwetter.  I must have misremembered.  Perhaps it was added in Ruby 2.1.

**Comment by abinoam** [comment]
Hi @elyscape , 

I've opened the PR #134 . I think we should drop 1.8 support. Do you actively use highline on any 1.8 project?

Look:
__1.8.7__ - Retired since 2013-06-30 - https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/

No bug fixes! Not even security fixes for 1.8!

Look at this gists https://gist.github.com/abinoam/020f3da3aa1e7339af4f

**Comment by elyscape** [comment]
I don't, no, but it is the standard version on EL6 and therefore still in heavy use despite its deprecated status. While I think dropping support would be fine, if you do so I highly recommend yanking 1.7.0 and putting out a 1.7.1 release that requires Runy >=1.9.3.

**Comment by JEG2** [comment]
This sounds like a pretty reasonable approach.

**Comment by abinoam** [comment]
:+1:  @JEG2 

@elyscape I'll do that now and prepare for release.

**Comment by abinoam** [comment]
Closing. We'll not support 1.8 anymore.
