### ISSUE TITLE
Fail to install from zip download

### ISSUE THREAD

**Issue by StinkyDragon** [JEG2/highline#141]
Hi Guys!

Thank you for the gem, I am certain it works great.

I have initially failed to install it because
the highline.gemspec assumes I got the git repo
and uses 'git ls-files' to get the file lists.

But I did not use git,
I just downloaded the snapshot zip file from github:
wget https://github.com/JEG2/highline/archive/v1.7.2.zip

Running 'ruby setup.rb' also fails,
first for a duplicated index (which I removed from the code)
then for this:
ruby setup.rb
setup.rb:259:in `<main>': uninitialized constant Config (NameError)

Cloning the whole repo works,
but usually this is not my preferred method.

I hope this helps to polish the code even further!

**Comment by JEG2** [comment]
Hmm, this is a good point.  However, it's also a very standard practice now.  Bundler generates code like this when setting up a gem for you, so I assume a lot of gems have this issue, right?

**Comment by StinkyDragon** [comment]
I am new to ruby, so I can not tell how frequent this issue is.
The few other gems I tried so far did install fine from the zip file,
but they might just not use the bundler.

I looked at the termios.gemspec and that has the file list hardcoded,
which is OK for smaller gems and is probably not efficient for larger ones.
You might open a ticket for the Bundler guys, I have no account there
and I'd rather not open one just for this.

**Comment by JEG2** [comment]
@abinoam Thoughts?

**Comment by abinoam** [comment]
I can take a look at it this week.
Now I'm away from my computer.
But, my first impression is the same of yours @JEG2

Just for the sake of curiosity, why 'gem install highline' is not an option
for you StinkyDragon? (What is your use case?)

Em Seg, 22 de jun de 2015 14:48, James Edward Gray II <
notifications@github.com> escreveu:

**Comment by abinoam** [comment]
Hi @StinkyDragon,

I think you could try to "force" a install by changing the line at the highline.gemspec

From:
```ruby
spec.files = `git ls-files`.split("\n")
spec.test_files  = `git ls-files -- test/*.rb`.split("\n")
```

To:
```ruby
spec.files = Dir.glob("{bin,lib}/**/*")
spec.test_files = Dir.glob("test/**/*")
```

After that you should issue a:
```sh
rake package
```

The above will create a file at the ```pkg``` directory so you could install it.

If you have any problem with the code_statistics gem not being installed you could just drop its line on Rakefile. Remove the ```require "code_statistics"``` on Rakefile

And now you install highline as a gem with:

```sh
gem install pkg/highline-1.7.2.gem
```

I wouldn't change the HighLine behaviour now. Bundler still recommends the git-ls approach.
I've just tested on bundler version 1.10.4
```ruby
spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
```

But I recognize that this issue affects a lot of people.
This issue in bundler github repo links to a lot of other issues
https://github.com/bundler/bundler/issues/2287

My main concern in favor of ```git ls-files``` approach is that I don't have to care about "trash" files around at packaging time. It will only package those that are committed to the repo. The Dir.glob approach packages everything that could possible be lying around.

Perhaps we could make an _alternative_ rake task that points to a different .gemspec file with Dir.glob approach?! 
Or make the official .gemspec to fallback to Dir.glob when git is not available?!

**Comment by abinoam** [comment]
The current bundler newgem template is here
https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/newgem.gemspec.tt

**Comment by StinkyDragon** [comment]
Sorry for the delayed response,
my access is intermittent.

a) Why not to use on-line tools to install things:

a1) Because on-line tools frequently pull down the 'newest and latest' version, so if someone prepares a procedure to 'install the following things' the actual version of those things will depend on when the procedure will be done. Including the actual files to be installed / applied avoids getting the wrong version, ensures getting a version that was tried and tested.

a2) Because applications might be installed on machines that are not connected to the internet. Procedures that say 'download X' (or 'git clone that') do not work well on those machines.


b) Modifying the gemspec file

b1) I understand why using the git index avoids picking up junk files, so I think this is one of those cases where one has to understand and live with the downside to get the benefit of the upside.

As long as you keep the directories clean you could just include a description of the changes to be made to the gemspec file for off-line build in the INSTALL instructions.

b2) Being new, I do not use Rake, I do not have it installed, I do not even know what it is (for). Consequentially I do know what a Rakefile is.

I will try a "gem build highline.gemspec" tomorrow on the modified gemspec file, will let you know if it works / fails.


c) Thank you guys for all the help and good intention.

**Comment by JEG2** [comment]
> a) Why not to use on-line tools to install things:

I want to address at least a few of these points.

> a1) Because on-line tools frequently pull down the 'newest and latest' version, so if someone prepares a procedure to 'install the following things' the actual version of those things will depend on when the procedure will be done.

RubyGems can [install any version](http://stackoverflow.com/questions/17026441/how-to-install-a-specific-version-of-a-ruby-gem) of a gem that you like.

> a2) Because applications might be installed on machines that are not connected to the internet. Procedures that say 'download X' (or 'git clone that') do not work well on those machines.

RubyGems can [install local files](http://stackoverflow.com/questions/220176/how-can-i-install-a-local-gem).

> b2) Being new, I do not use Rake, I do not have it installed, I do not even know what it is (for). Consequentially I do know what a Rakefile is.

Rake comes with Ruby.  That's why we count on you having it and give instructions based on it.  It's a tool used to automate maintenance tasks, like the one you are facing here.

**Comment by StinkyDragon** [comment]
Sorry, I keep having trouble with my GitHub password.

*) The modified gemspec file had worked, thank you. The resulting gem seems to work, obviously I had only tried some of the most basic functions so far.

*) Why do we call ruby's 'gem' command 'RubyGem' ? Nickname? Given Name? Way to confuse newbies? Whatever.

*) 'gem fetch' is mostly a glorified 'wget https://rubygems.org/....' (I have actually ended up putting the 'wget' commands into my procedure because it means that the gems can be downloaded on any computer, whether they have ruby installed or not. So in this sense using wget is superior to using 'gem fetch'.)

*) I understand that 'gem fetch' might do more that a simple wget, but in the effort of 'making it newbie friendly and stupid simple' most docs simply say: "type in this, and it will work". Few seems to talk about what that command actually does. This makes troubleshooting tricky. Wget wins on this too.

*) Installing the downloaded gems worked (including yours), except one (termios), so the 'get the prepackaged gem and just install' idea is apparently not fool proof.
On the other hand the nokogiri guys seem to go into extra length that you do not just download and compile their code, they do not even provide a gemspec file. Nice.

*) Your install file mentions that you can take advantage of the termios package if that is installed, but there are three termios packages on rubygems.org and the plain 'termios' is not the one most recently updated (by far), i.e. I do not know if that package is still maintained or not. Do you recommend the plain 'termios' package from rubygems?

*) And again, I do appreciate your effort to help and educate.
I had a crazy day yesterday and today is not looking any easier, but I will google up 'rake' and try to figure what is the difference between that and just a plain 'gem build'.

(My real problem is that ruby seems to be a language with some deep features, like Classes, Modules, build systems, etc. but I just have no time to actually learn any of those, I am on time pressure to get something working NOW using a third party ruby gem. Meanwhile we are not a ruby shop, i.e. I have no one to ask advice from. But cookbooks and copy/paste seem to have carried this project so far.)

**Comment by JEG2** [comment]
> *) Why do we call ruby's 'gem' command 'RubyGem' ? Nickname? Given Name? Way to confuse newbies? Whatever.

I would say it's fairly common in Unix for command-line binaries to have shortened names:  "list" is _ls_, "make directory" is _mkdir_, etc.

> *) 'gem fetch' is mostly a glorified 'wget https://rubygems.org/....' (I have actually ended up putting the 'wget' commands into my procedure because it means that the gems can be downloaded on any computer, whether they have ruby installed or not. So in this sense using wget is superior to using 'gem fetch'.)

If you don't have Ruby installed, you can't install a gem.  :smile:

> *) Your install file mentions that you can take advantage of the termios package if that is installed, but there are three termios packages on rubygems.org and the plain 'termios' is not the one most recently updated (by far), i.e. I do not know if that package is still maintained or not. Do you recommend the plain 'termios' package from rubygems?

Yes, it's the `termios` gem.

**Comment by JEG2** [comment]
> *) Installing the downloaded gems worked (including yours), except one (termios), so the 'get the prepackaged gem and just install' idea is apparently not fool proof.

You are choosing to do manual installs, because you prefer that scenario, right?  That means, among other things, you are choosing to manually manage you dependancies.  That's all part of the tradeoff you have selected.

**Comment by StinkyDragon** [comment]
Wow. My password had worked!
I guess colons don't work well in github passwords, that could have been the underlying cause of my troubles.

*) Since we do not use ruby normally we do not have ruby on most of the machines. The guy who puts together the deployment kit will have to get the files somehow, even though otherwise he might not use ruby ever. Installing ruby just so that he can run 'gem fetch' is a bit overkill.

Once he put together the deployment kit, it will go to some place (think of a farm out in the big nowhere) where internet access is slow and spotty. Hence all files to be installed are better to be included in the kit.

*) I know the scenario I am describing here is NOT the one most ruby developers have in mind. Most ruby tools (rvm anyone?) are tuned for users who have broadband connections and like the idea that the tool takes care of everything. Which is very nice and convenient.

We are one of those minority users who can not take advantage of these features.

*) So why ruby? Because we are going to support a third party tool that comes with a ruby API.

Anyhow, I am not sure I can add much useful info here.
I guess you could close the bug, unless you want to add the extra info into the INSTALL file first to help other off-line folks.
I have not tried rake but I will read up on it, I promise.

**Comment by JEG2** [comment]
@abinoam ↑ your call.

**Comment by abinoam** [comment]
Good comments @JEG2 ,

Happy that you have found your way to make it work.

In a quick searching I could find this link
http://stackoverflow.com/questions/11291235/ruby-gem-dependencies-on-offline-server

It suggests a combination of ```bundle package``` and ```bundle install --local``` 

I'll close this issue
Later I could try to find the 'proper' way to have a bundle for installing HighLine in an offline environment.
(No guarantee I could do this soon).
