### ISSUE TITLE
Highline::Simulate error

### ISSUE THREAD

**Issue by bparanj** [JEG2/highline#142]
When I run:
```ruby
require 'minitest/autorun'
require 'highline/simulate'

class SimulatorTest < Minitest::Test
  
  def test_simulator  
    HighLine::Simulate.with(['Bugs Bunny']) do
      name = ask('What is your name?')
      
      assert_equal 'Bugs Bunny', name
    end
  end
end
```

I am getting this error:
```sh
SimulatorTest#test_simulator:
RuntimeError: can't modify frozen NilClass
    /Users/bparanj/.rvm/gems/ruby-2.2.2@ajey/gems/highline-1.7.2/lib/highline/simulate.rb:45:in `instance_variable_set'
    /Users/bparanj/.rvm/gems/ruby-2.2.2@ajey/gems/highline-1.7.2/lib/highline/simulate.rb:45:in `ensure in with'
    /Users/bparanj/.rvm/gems/ruby-2.2.2@ajey/gems/highline-1.7.2/lib/highline/simulate.rb:45:in `with'
    scripts/prank_test.rb:9:in `test_simulator'
```

How do I use the simulate class to fake user input?

**Comment by JEG2** [comment]
I suspect this is due to a change in Ruby 2.2.2.  `nil` is now frozen.  We must have some code that doesn't play well with this change.  We'll need to find out what's causing the incompatibility and work around it.

Just FYI, I am currently on vacation until the end of July.

**Comment by bparanj** [comment]
No problem. I will try with older Ruby versions.

**Comment by abinoam** [comment]
I can take a look at it later today.

Em Dom, 28 de jun de 2015 23:19, Bala Paranj <notifications@github.com>
escreveu:

**Comment by abinoam** [comment]
Hi @bparanj ,

Try
```ruby
HighLine::Simulate.with("Bugs Bunny") do
```
without encapsulating it inside an array.

And... don't forget to tell us if it works on your environment :wink: !

HighLine::Simulate.with is already doing that for you at

https://github.com/JEG2/highline/blob/master/lib/highline/simulate.rb#L40
```ruby
    def self.with(*strings)
```

Look at the ```*``` 

Thanks for noting this. I'll try to put your tests and some documentation on it.

**Comment by bparanj** [comment]
I just verified it on ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13] on my Mac. Your tests are working. Thanks.
