### ISSUE TITLE
stty error when doing standard ask followed by echo = '*'

### ISSUE THREAD

**Issue by akerl** [JEG2/highline#152]
I'm seeing `stty: standard input: unable to perform all requested operations` when submitting an ask response with echo = '*' or echo = false. I've whipped up a quick test script:

```
#!/usr/bin/env ruby

require 'highline/import'

test_case = ARGV.first

case test_case
when '1'
  puts "Prompting for standard then no-echo"
  ask('A: ')
  ask('B: ') { |q| q.echo = '*' }
when '2'
  puts "Prompting for no-echo then no-echo"
  ask('C: ') { |q| q.echo = '*' }
  ask('D: ') { |q| q.echo = '*' }
end
```

```
# ruby foo 1
Prompting for standard then no-echo
A: a
B: *stty: standard input: unable to perform all requested operations


# ruby foo 2
Prompting for no-echo then no-echo
C: *
D: *
```

Here's my current versions for ruby/highline:

```
# ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

# gem list highline

*** LOCAL GEMS ***

highline (1.7.3)
```

**Comment by akerl** [comment]
To rule out new-ruby issues, confirmed I get the same result with 1.9.3. I also get this on both bash and zsh:

```
❯ ruby -v
ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-darwin13.4.0]
~/src/dock0/vm_config ()* mazer
```

```
# bash --version
bash --version
GNU bash, version 4.3.39(1)-release (x86_64-apple-darwin14.4.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
❯ zsh --version
zsh 5.0.8 (x86_64-apple-darwin14.3.0)
```

**Comment by abinoam** [comment]
Hi @akeri

I'll try to take a look at it tomorrow.
But, would you mind testing the edge branch?

https://github.com/abinoam/highline/tree/refac_styles

Could you clone it and run ```rake acceptance``` inside it.
Just copy and past the result here.
Thank you any way.

**Comment by abinoam** [comment]
@akerl , I'm trying to reproduce the issue without succes.
I'll keep trying.

**Comment by akerl** [comment]
```
❯ cat highlinetests-20150905100527.log

===
Well done!

Below you have a report with all the answers you gave.
It has also some environment information to help us debugging.

If any of the tests have not passed on your environment,
please copy/past the text bellow and send to us.

If you are familiar with GitHub you can report the failing test
as a GitHub issue at https://github.com/JEG2/highline/issues.
If possible, always check if your issue is already reported
by someone else. If so, just report that you are also affected
on the same alredy open issued.

If you are more confortable with e-mail, you could send it to
james@grayproductions.net

=== HighLine Acceptance Tests Report
Date: 2015-09-05 14:05:27 UTC
HighLine::VERSION: 2.0.0-develop.2
Terminal: HighLine::Terminal::IOConsole
RUBY_DESCRIPTION: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
Readline::VERSION: EditLine wrapper
ENV['SHELL']: /opt/boxen/homebrew/bin/zsh
ENV['TERM']: xterm-256color
ENV['TERM_PROGRAM']: iTerm.app

Answers:
at_color_output_using_erb_templates.rb: y
at_echo_false.rb: y
at_readline.rb: y
```

That said, I only see this when I do a echo = false *after* an echo = true, so I'd not expect it to present in the acceptance test as it currently runs

**Comment by akerl** [comment]
On the upside, even with this weird thing (which I expect will be some weird ruby version / system version / etc collision), this is all still entirely usable, despite the weird error message

**Comment by abinoam** [comment]
Hi @aker,

Just for curiosity... Do you know why your Readline::VERSION shows as EditiLine wrapper?

My output is like this
```
=== HighLine Acceptance Tests Report
Date: 2015-09-05 14:47:35 UTC
HighLine::VERSION: 2.0.0-develop.2
Terminal: HighLine::Terminal::IOConsole
RUBY_DESCRIPTION: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
Readline::VERSION: 6.2
ENV['SHELL']: /bin/bash
ENV['TERM']: xterm-256color
ENV['TERM_PROGRAM']: iTerm.app
```

By the way, this develop version of HighLine it "automatically" issues an echo = false and then and echo = true.

Try this, to see if we can isolate the issue

```ruby
require 'io/console'

puts "Setting echo = true"
STDIN.echo = true

puts "Trying to get a character with #getch"
one_char = STDIN.getch
puts "Got #{one_char.inspect}"

puts "Trying to get a character with #getc"
one_char = STDIN.getc
puts "Got #{one_char.inspect}"

puts "Setting echo = false"
STDIN.echo = false

puts "Trying to get a character with #getch"
one_char = STDIN.getch
puts "Got #{one_char.inspect}"

puts "Trying to get a character with #getc"
one_char = STDIN.getc
puts "Got #{one_char.inspect}"
```

**Comment by abinoam** [comment]
Could you also issue a 

```bash
which stty
```

My output is
```
/bin/stty
```

**Comment by akerl** [comment]
I believe I've isolated it to when this is used with GNU coreutils from homebrew. My stty is generally /opt/boxen/homebrew/opt/coreutils/libexec/gnubin/stty. Substituting in /bin/stty doesn't cause the same error.

```
irb(main):004:0> system 'stty 6b02:3:4b00:5cf:4:ff:ff:7f:17:15:12:0:3:1c:1a:19:11:13:16:f:1:0:14:0;'
stty: standard input: unable to perform all requested operations
=> false
irb(main):005:0> system '/bin/stty 6b02:3:4b00:5cf:4:ff:ff:7f:17:15:12:0:3:1c:1a:19:11:13:16:f:1:0:14:0;'
=> true
```

**Comment by abinoam** [comment]
Hi @akerl ,

Sorry for the late response. I just lost this message.
We could try to make a patch where you could point to the correct ```stty` with some environment variable and/or set it at runtime. Do you think this could help?

**Comment by akerl** [comment]
It would, but I think the saner solution is for me to just fix my local PATH so the stty used is functional.

If, as a dev, you have to plan around arbitrary binaries on the system being broken, things get really gnarly really fast :)

I'll just symlink the good stty to an earlier spot in my path and that'll sort things out.

Thanks for helping point me in the right direction for troubleshooting.

**Comment by abinoam** [comment]
@akerl, Thanks for your feedback!
