### ISSUE TITLE
Can't dup Symbol 

### ISSUE THREAD

**Issue by 97-109-107** [JEG2/highline#159]
I'm a user of an email client called [sup](https://github.com/sup-heliotrope/sup) which relies on highline. Since recent updates to my system (including gems) I get the following error:
````
--- TypeError from thread: main
can't dup Symbol
/home/xxx/.gem/ruby/2.2.0/gems/highline-1.7.6/lib/highline/question.rb:34:in `dup'
/home/xxx/.gem/ruby/2.2.0/gems/highline-1.7.6/lib/highline/question.rb:34:in `initialize'
/home/xxx/.gem/ruby/2.2.0/gems/highline-1.7.6/lib/highline.rb:252:in `new'
/home/xxx/.gem/ruby/2.2.0/gems/highline-1.7.6/lib/highline.rb:252:in `ask'
/home/xxx/Opt/sup/lib/sup/modes/scroll_mode.rb:82:in `search_in_buffer'
/home/xxx/Opt/sup/lib/sup/mode.rb:59:in `handle_input'
/home/xxx/Opt/sup/lib/sup/buffer.rb:222:in `handle_input'
/home/xxx/Opt/sup/bin/sup:297:in `<module:Redwood>'
/home/xxx/Opt/sup/bin/sup:116:in `<main>'
````
I understand that the problem might be 'higher up' than the library itself, but in a rare case that it isn't - I'm politely posting it here.

*I reported this to sup maintainers as well - [here](https://github.com/sup-heliotrope/sup/issues/477)*

**Comment by abinoam** [comment]
Thank you for reporting it.
I'll take a look at it.
Could you tell me what is the version of sup you're running so I can test with the same version.
I see you're using the 1.7.6 version of HighLine.

**Comment by abinoam** [comment]
For reference:
- https://github.com/sup-heliotrope/sup/issues/477
- https://github.com/sup-heliotrope/sup/issues/473#issuecomment-142445940 (My comment on another 'related' issue)

**Comment by 97-109-107** [comment]
I'm not sure if you still need this information, but I'm running 7989b5b

Thank you for your prompt response.

Your [fix](https://github.com/JEG2/highline/pull/160) resolved this issue, but I'm seeing some other weird behaviour. Stil investigating.

**Comment by abinoam** [comment]
The issues are probably related to my comment on sup-heliotrope/sup#473
Thanks again for reporting!
