### ISSUE TITLE
Multiple answers menu possible?

### ISSUE THREAD

**Issue by tukanos** [JEG2/highline#187]
Hi,
I tried to read the Rdoc for HighLine but could not find a solution for such menu.  Maybe someone has found a simple way of doing such menu?  (you can do it with multiple ask(s) and numbers but that is not the point).

How would you do the following:
Select courses for your menu:
[ ] appetizer
[ ] soup
[ ] main dish
[ ] desert 

User should select a menu like this:
[ ] appetizer
[x] soup
[x] main dish
[ ] desert 

Which would end up in the Array `[:soup, :main_dish]`.  I thought that could be done via numbers selecting multiple answers or maybe interactive (I presume that would be hard)?

Thank you,

**Comment by abinoam** [comment]
ncurses (with all sort of dependency related problems attached) it's what comes to my mind.
Currently no support for that (that I can remember).

**Comment by abinoam** [comment]
Hi @tukanos,
Closing this. Feel free to reopen it if you need.
