### ISSUE TITLE
Agree default option not working when character is set

### ISSUE THREAD

**Issue by maurobender** [JEG2/highline#192]
When __character__ option is set to _true_ for an agree question the default option is ignored

Example:
```ruby
agree('Do you agree? (yes/no) ', true) {  |q| q.default = 'no' }
```
Ouput: 
```sh
Do you agree? (yes/no) |no| _
```
But when a hit _Enter_ it says that the chosen option is not valid and prompt me again with the same question.

**Comment by abinoam** [comment]
Hi @maurobender,

This is affecting only the ```stable``` branch.
Please try to install the pre-release version with 
```gem install --pre highline```
I'm closing this issue as solved.
Feel free to reopen it if you need.
