### ISSUE TITLE
Question Confirm to execute Proc

### ISSUE THREAD

**Issue by mmihira** [JEG2/highline#198]
It would be useful if the question.confirm attribute also accepted a Proc object, which when executed would return the confirm question to ask.

If you guys are ok with the idea I will implement it and submit a pull request ?

**Comment by abinoam** [comment]
It sounds reasonable to me. Tell us if you find any difficult navigating
the code base. We'll be happy to help you.

>

**Comment by abinoam** [comment]
Completed at #201
