### ISSUE TITLE
suppress newline echo to stdout

### ISSUE THREAD

**Issue by txt8888** [JEG2/highline#206]
how to prevent the newline after the password was entered from being echo to stdout?

ruby and  highline version:
```
ruby -r highline -ve 'p [HighLine::VERSION, HighLine::SystemExtensions::CHARACTER_MODE]'
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
["1.7.8", "stty"]

```

file: testhl.rb

```
#!/usr/bin/env ruby

require 'highline'

prompt  = HighLine.new($stdin, $stderr)
name    = prompt.ask("name: ") { |q| q.echo = '.' }

$stdout.puts "hello, #{name}"
```

```
$ ./testhl.rb > out.txt
name: john

```
the out.txt file always has a newline character at the beginning.  i.e :  ` \nhello, john`. anyway I can prevent that \n ?

**Comment by abinoam** [comment]
Hi @txt8888,

Thanks for contributing an issue to HighLine.

This newline isn't from the grabbed string itself. 
It's being put there by... well... ```puts``` :wink:

Try this snippet (a modified version of yours).

```ruby
#!/usr/bin/env ruby

require 'highline'

prompt  = HighLine.new($stdin, $stderr)
name    = prompt.ask("name: ") { |q| q.echo = '.' }

$stdout.puts "hello, #{name}. 'puts' is putting the newline"
$stdout.print "print doesn't do this with #{name}"
```

If this solve your issue, please let us know so we can close this.
But, feel free to add any comment you want.

**Comment by abinoam** [comment]
Dear @txt8888, 

Any feedback on your issue. Have my answer solved it?

I'm closing this issue by now. But you can comment or reopen it if you feel you need it.
