### ISSUE TITLE
Docs not on RubyDoc.info as README states

### ISSUE THREAD

**Issue by jblaine** [JEG2/highline#217]
Links in README are dead.

http://www.rubydoc.info/find/github?q=highline = no results

**Comment by abinoam** [comment]
Hi @jblaine,

The link at README is http://www.rubydoc.info/github/JEG2/highline/master and it seems to be working (at least at the time I could reach to it).

But, you're right, I can't get the highline docs from the Rubydoc.info search form (The link you have posted).

Strangely, if you click at the letter "H" (http://www.rubydoc.info/github/~h) it will appear normally.

By the way, I have (re)added github highline project at Rubydoc.info just to be sure. Let's see if it's just Rubydoc.info taking some time to rebuild a kind o search cache or so.

Thanks for reporting!

**Comment by abinoam** [comment]
Closing this as resolved.

PS:
Funny, if you search for "highlin" it will find it. But it won't find "highline"
See at: 
http://www.rubydoc.info/find/github?q=highlin
http://www.rubydoc.info/find/github?q=highline
