### ISSUE TITLE
Incosistent behavior when ask with a validator and readline=true

### ISSUE THREAD

**Issue by ailisp** [JEG2/highline#221]
Hi, we're using highline in a console for a cloud management platform: https://github.com/manageiq/manageiq-appliance_console. Recently we add all `Highline.ask` with `readline=true` option to add arrow key navigation. It works fine for no validator `ask`, but for cases with a validator, like `Highline.agree` or `Highline.choose`, it's behavior is inconsistent with the same method call of  `readline=false` option. Though we use a previous version of highline, but I just test with current master branch and inconsistency still exist.  For a minimum example, try some invalid input to these two `agree`:

```ruby
#!/usr/bin/env ruby
require 'highline'

def agree_readline(prompt)
  HighLine.new.agree(prompt) do |q|
    q.readline=true
  end
end

def agree(prompt)
  HighLine.new.agree(prompt)
end

agree_readline("agree readline=true? ")
agree("agree readline=false? ")
```
Similar problems for `choose` or manually call `ask` given validator. I did some hacks in our project to make them lo behave the same way as `readline=false`. But I think it's better to fix here.

**Comment by abinoam** [comment]
Hi @ailisp,

Thanks for reporting the issue.
What exactly is happening on your setup? 
What **behaviour** is inconsistent?

**Comment by ailisp** [comment]
Hi @abinoam Thanks for quick response. In a clone of current master branch. save the content I provide as example as test.rb:
```
[boyao@new-host highline]$ bundler exec ./test.rb
agree readline=true?aaa
Please enter "yes" or "no".
agree readline=true?
agree readline=true?
Please enter "yes" or "no".
agree readline=true?
agree readline=true?yes
agree readline=false?
aaa
Please enter "yes" or "no".
agree readline=false?

Please enter "yes" or "no".
agree readline=false?
yes
```
I input `aaa`, nothing and `yes` for both case (`readline=true` or `false`), and you can see with `readline=true` there's no extra newline after question, and redundant question. 
For `choose`, if we have `readline=true` then give a invalid input, the question and menu will display again, but for `readline=false` only question will display again.

**Comment by abinoam** [comment]
I think I understood.

I've had a quick look at the code now and couldn't figure out a quick fix.
I'll try to take a look at it next week and try to fix it or at least provide a way to work around it.

👍

**Comment by abinoam** [comment]
I see that the use of `readline = true` at `agree` is pretty much unimplemented.
It doesn't even autocomplete for **yes** or **no**.

**Comment by ailisp** [comment]
Yes. just noticed the auto complete part is not implemented. And here's of some hacks I did for make `choose` and `agree` looks the same as `readline=false`, it works but with some ugly hacks so I don't make a PR here direcly. I think you're more familiar with GNU Readline, but hope this can save you some time.
- readline replacement of `agree`
https://github.com/ManageIQ/manageiq-appliance_console/pull/6/files#diff-11f3fdac8dc445b3e93dd2459f62b9a9
- readline replacement for `choose`, based on a modified  `ask`, some observations of my experiments are in comments
https://github.com/ManageIQ/manageiq-appliance_console/pull/6/files#diff-70eae34541a813654c1e209ef9e093f4

**Comment by abinoam** [comment]
@ailisp Could you please have a look at PR #222 ?

**Comment by ailisp** [comment]
@abinoam Just tested with `ask` and `choose`, `readline=true` works consistently as expected and ompletion also works. Thanks for the fix!

**Comment by abinoam** [comment]
Thank you very much @ailisp! I'll merge it and release it. 👍

**Comment by abinoam** [comment]
Released https://rubygems.org/gems/highline/versions/2.0.0.pre.develop.14
