### ISSUE TITLE
Default Highline Example on GithubGives Error

### ISSUE THREAD

**Issue by billbisco** [JEG2/highline#225]
When I copy/paste the default Highline Example from Github into Cloud9 there is an error on line 49

# Using colored indices on Menus

HighLine::Menu.index_color   = :rgb_77bbff # set default index color  #line 49

/home/ubuntu/workspace/Project/Testing.rb:49:in `<main>': undefined method `index_color=' for HighLine::Menu:Class (NoMethodError)

When I installed the gem, everything else prior worked.

**Comment by abinoam** [comment]
Thanks for reporting the issue @billbisco.

Could you please check what is returned by...

```ruby
HighLine::VERSION
```

I suspect you're using the 1-7-stable branch. And the README.md examples are for 2.0.0-develop branch.

**Comment by abinoam** [comment]
Hi @billbisco, can you check what version are you running?

**Comment by mediamagnet** [comment]
Hello,

I'm getting the same error when using the example I'm using version 1.7.10.

**Comment by iranakam** [comment]
I also tried it with 1.7.10, and ```NoMethodError``` was reproduced.
However, as @abinoam said, I confirmed that it's not reproduced in 2.0.0.pre.develop.14.

**Comment by abinoam** [comment]
As @iranakam confirmed @billbisco is probably running the example using the wrong version. I'll close this for now. Anybody feel free to reopen the issue if think appropriate.
