### ISSUE TITLE
Issues with echo: false and not on TTY

### ISSUE THREAD

**Issue by cabello** [JEG2/highline#237]
Hi 👋 ,

We've been using highline with much success! 🎉  Thanks for making this project open source.

I just noticed an issue present in both 1.7 and 2.0 when executing scripts not in a TTY and setting `echo` to `false`.

Script to reproduce issue `script.rb`:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'highline',  '~> 2' # change this to ~> 1 to test 1.X.
end

cli = HighLine.new
answer = cli.ask("What do you think?") { |q| q.echo = false }
puts "You have answered: #{answer}"
```

Command to reproduce the issue: `echo 'something' | ruby script.rb`

Output in 2.x:
```
What do you think?
Traceback (most recent call last):
	10: from highline_feature_request.rb:9:in `<main>'
	 9: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline.rb:223:in `ask'
	 8: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline/question_asker.rb:30:in `ask_once'
	 7: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline/question.rb:536:in `get_response_or_default'
	 6: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline/question.rb:524:in `get_response'
	 5: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline.rb:518:in `get_response_line_mode'
	 4: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline.rb:538:in `get_line_raw_no_echo_mode'
	 3: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline/terminal.rb:70:in `raw_no_echo_mode_exec'
	 2: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline/terminal.rb:70:in `ensure in raw_no_echo_mode_exec'
	 1: from /Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline/terminal/io_console.rb:20:in `restore_mode'
/Users/danilo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/highline-2.0.0/lib/highline/terminal/io_console.rb:20:in `echo=': Inappropriate ioctl for device (Errno::ENOTTY)
```

It **breaks** and there is no recovery after that. It works as expected when `echo` is `true`.

Output in 1.X:
```bash
What do you think?
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal

You have answered: something
```

It **works** even though it includes warnings.

Thanks again 💜

**Comment by abinoam** [comment]
Great catch. Confirmed in my machine. I can't promise taking a look at it really quickly. But I'll try it at least next week. (If you see a patch before this, please open a PR). This may have a huge impact in running scripts in pipes.

Thank you.

**Comment by abinoam** [comment]
Perhaps related to https://github.com/piotrmurach/tty-prompt/issues/49

**Comment by abinoam** [comment]
Well, currently we treat input, output as being from the same "type". But when pipeing input can be a file and output a terminal.

**Comment by abinoam** [comment]
I've just assembled a quick and dirt fix.
Released https://rubygems.org/gems/highline/versions/2.0.1
@cabello could you please give me any feedback if this fix is enough for your software.
I'll probably look at this later for a better solution.

**Comment by abinoam** [comment]
The HighLine's assumption that input and output is the same type is broken.

**Comment by cabello** [comment]
I just confirmed this works as expected. Thanks for the quick fix.
