### ISSUE TITLE
echo=false or echo='*' requires extra character after enter on Windows

### ISSUE THREAD

**Issue by galinkinlin** [JEG2/highline#244]
```
highline = 2.0.2
ruby = ruby 2.5.5p157
Windows 10
```
Hey there!

```require 'highline/import'

ask('Enter Password:') do |x|
  x.echo = false
 # or x.echo = '*'
end 
```

The above script requires an extra character to be entered in the command line after enter is hit on windows before it releases back to the rest of the script (I'm using CMD, but I believe it happens with conemu and powershell, too).

**Comment by mkalan** [comment]
I too am having this exact same issue.

**Comment by abinoam** [comment]
I'll try to have a look as soon as possible. Meantime if someone come up with a patch, please submit a PR.

**Comment by orgads** [comment]
The problem is in io/console. This can demonstrate it as well:

```
require 'io/console'

c = nil
while c != "\r" && c != "\n"
  c = STDIN.getch
  STDERR.puts c.ord
end
```

**Comment by orgads** [comment]
https://github.com/ruby/io-console/issues/3

**Comment by abinoam** [comment]
Great @orgads so it's better to wait for a fix at io/console itself.

**Comment by abinoam** [comment]
https://github.com/ruby/io-console/issues/3 says it is solved and closed already. 

Thank you all.
