### ISSUE TITLE
Some test failures on Windows

### ISSUE THREAD

**Issue by kachick** [JEG2/highline#59]
All test passes on MacOSX.
But some failures on Windows.

Environment(Windows)
--------------------------------

* Windows7 64bit
* ruby 1.9.3p362 (2012-12-25) [i386-mingw32]
* Head(e785e6e4b03fabd108ac9cd7de0d5afa4860e6a4)

```ruby
p HighLine::SystemExtensions::CHARACTER_MODE #=> "Win32API"
```

TestResult
----------------

```
Finished tests in 0.359375s, 256.0000 tests/s, 2148.1739 assertions/s.

  1) Failure:
test_backspace_does_not_enter_prompt(TestHighLine) [E:/GitHub/highline/test/tc_highline.rb:158]:
<""> expected but was
<"\b\b">.

  2) Failure:
test_character_echo(TestHighLine) [E:/GitHub/highline/test/tc_highline.rb:136]:
<"Please enter your password:  ********\n"> expected but was
<"Please enter your password:  *********\n">.

92 tests, 772 assertions, 2 failures, 0 errors, 0 skips
```

Note
------

An warning occured.

```
Warning:C:/Ruby193/lib/ruby/1.9.1/rubygems/custom_require.rb:36: Win32API is dep
recated after Ruby 1.9.1; use dl directly instead
```

**Comment by abinoam** [comment]
Hi @kachick and @davispuh , 

We're refactoring HighLine and we will probably be relying on 'io/console' (included in recent versions of Ruby) for our 'low-level' work.

I've just made some adjustments and had tested with Ruby 2.2 from RubyInstaller

All (but one) tests are passing. The failing test is related to encoding and I'll take a look at it later.

Could you (@kachick and @davispuh) have a look at this PR #149 and run the tests on your machines to confirm it works for you?

**Comment by davispuh** [comment]
Yeah, works fine, all tests pass. Tested on both CMD and PowerShell.

```
# Running:
..................................S..S...S.....................................S.............................................................
Finished in 0.223857s, 629.8675 runs/s, 4498.4157 assertions/s.
141 runs, 1007 assertions, 0 failures, 0 errors, 4 skips
```

```
=== HighLine Acceptance Tests Report
Date: 2015-07-23 15:36:08 UTC
HighLine::VERSION: 2.0.0-develop.2
Terminal: HighLine::Terminal::IOConsole
RUBY_DESCRIPTION: ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
Readline::VERSION: 5.2
ENV['SHELL']: 
ENV['TERM']: 
ENV['TERM_PROGRAM']: 

Answers:
at_color_output_using_erb_templates.rb: y
at_echo_false.rb: y
at_readline.rb: y
```

**Comment by abinoam** [comment]
Great!
Thank you @davispuh 

I have also added Appveyor to the repo (Continuous Integration for Windows) https://github.com/abinoam/highline/commit/1c32748d814e06ac7ad556afc5dfc0ce50203c4b

We will make some effort to keep Windows compatible from now on.

Appveyor urls:
The master: https://ci.appveyor.com/project/abinoam/highline
My personal fork: https://ci.appveyor.com/project/abinoam/highline-c4m2m

**Comment by abinoam** [comment]
PR #149 merged. So closing this issue.

**Comment by kachick** [comment]
@abinoam :+1:
