### ISSUE TITLE
terminal_size return nil in some environments in Linux

### ISSUE THREAD

**Issue by boutil** [JEG2/highline#85]
Hi,
In some environments on Linux, stty returns an empty string, which means that terminal_size returns nil instead of integers. This causes test_terminal_size test in test/tc_highline.rb, line 932 to fail.

Examples of such environments are the clean environment created by pbuilder and sbuild in Debian to build packages. It probably can happen on other occasions.

If you want to insist on terminal size to return Fixnums, should terminal_size return a size of 0 if stty cannot return the size of the terminal? 

Cheers,

Cédric

**Comment by abinoam** [comment]
Hi @boutil and @JEG2 ,

What about just falling back to the old and gold 80x24 terminal size when stty doesn't get the size correctly? 

It fixes temporarily until interested people implement support for getting the terminal size for specific system with other methods (not stty size).

What do you think?

**Comment by abinoam** [comment]
I could "reproduce" the issue with a stdin redirection at command line:
```sh
rake test < anyfile.txt
```
It gives me 
```
[ 48/108] TestHighLine#test_terminal_sizestty: stdin isn't a terminal
 = 0.00 s
  1) Failure:
TestHighLine#test_terminal_size [/Users/abinoam/src/highline/test/tc_highline.rb:1098]:
Expected nil to be an instance of Fixnum, not NilClass.
```

**Comment by JEG2** [comment]
Could we use Ruby's standard `io/console` to get the size when `stty` returns nothing?  Just a thought.  I'm fine with the default too.

Could we use the `tty?()` method to detect `$stdin` redirects?  Not sure if that's helpful.

**Comment by abinoam** [comment]
Testing here.
IO.console.console_size is consistently getting terminal size even with redirections.
Doing some more testing.

**Comment by JEG2** [comment]
My fear though is that it could fail if run as a Cron job or in a similar minimized environment.  In which case we probably still need a default.  I can't decide if this is better or worse.

**Comment by abinoam** [comment]
We could sequentially try more than one method of getting terminal size and
fall back into a default if fail. I'll do some experimentation later and
give a report. Meanwhile, don't merge the PR.
Em 02/02/2015 12:45, "James Edward Gray II" <notifications@github.com>
escreveu:

**Comment by abinoam** [comment]
I don't understand clearly. 
IO.console.winsize is working well (I misspelled to console_size at my last comment).
IO.console_size not.
I'll try some code now.

**Comment by abinoam** [comment]
Hi JEG2, 

Using IO.console.winsize is really great. I also think we could refactor (later) most of the code to rely on it. (trimming all that tests for solaris, etc...)

What do you think of how the PR is now with this new commit?

**Comment by JEG2** [comment]
Looks awesome.  You went above an beyond the call.  Thank you.
