### ISSUE TITLE
Highline v1.6.2 Error

### ISSUE THREAD

**Issue by bsodmike** [JEG2/highline#98]
Hi James,

I was working on a chef setup with vagrant and hit a wall with it dying on https://github.com/JEG2/highline/blob/master/lib/highline.rb#L711

```
chef] Destroying VM and associated drives...
[chef] Running cleanup tasks for 'chef_solo' provisioner...
/Users/mdesilva/.vagrant.d/gems/gems/highline-1.6.20/lib/highline.rb:711:in `format_statement': undefined method `to_str' for {"chef-server"=>"2.0.0"}:Hash (NoMethodError)
	from /Users/mdesilva/.vagrant.d/gems/gems/highline-1.6.20/lib/highline.rb:617:in `say'
```

I've 'patched' it locally by hand by changing `to_str` to `to_s`.

**Comment by abinoam** [comment]
The main output method in Ruby is **#puts**.
**#puts** accepts anything as argument and it just convert it into a String.
So, when we see #say or #ask we naturally think we can pass any arbitrary object, like the hash that was being passed in https://github.com/berkshelf/solve/blob/v0.8.1/lib/solve/tracers/human_readable.rb#L43 and was fixed here https://github.com/berkshelf/solve/commit/6d7540867f5be9585a61dfbe66280bb2b178a082 just to work along with HighLine.
What about to give **#say** some of the  **#puts** superpowers?

The current problem is that **#say** is trying to #dup and #to_str the arguments. But some objects have problems with #dup, and others have problems with #to_str. 

So, I tried to improve on this by first calling String (conversion method), and #dup only after we have a String.
