### ISSUE TITLE
Honour termios settings (including VEOF) 

### ISSUE THREAD

**Issue by JEG2** [JEG2/highline#99]
See:

http://rubyforge.org/tracker/?func=detail&atid=2700&aid=29826&group_id=683

and:

http://rubyforge.org/tracker/?func=detail&atid=2700&aid=29827&group_id=683

**Comment by abinoam** [comment]
Hi @JEG2 , broken links in the house!

**Comment by JEG2** [comment]
Yeah, these are long gone.  Closing until we get another complaint.  (I don't remember the details.)
